### ISSUE TITLE
Completed User Authorization Cycle

### ISSUE THREAD

**Issue by MikeG212** [MikeG212/OfficeCamp#2]
# User Auth

## Functionality

- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

**Comment by jenvomo** [comment]
- Currently getting an error for invalid username or password  
- [x] Reduce width of signup and login form
- [x] Add padding around form / logo so its not touching top of the page
- [x] Reduce font size of form header to match basecamp
- [x] Add some space between form header and input fields
- [x] Add shadow around form to match basecamp
- [x] Add padding between buttons and end of form
OfficeCamp:
![screen shot 2018-10-17 at 11 19 59 am](https://user-images.githubusercontent.com/39272166/47107626-a54d3900-d1fe-11e8-848a-819aa1afe4cf.png)
Basecamp:
![screen shot 2018-10-17 at 11 20 06 am](https://user-images.githubusercontent.com/39272166/47107636-aaaa8380-d1fe-11e8-8028-6f41e4029867.png)

**Comment by jenvomo** [comment]
- [x] Fix Sign Up form styling
![screen shot 2018-10-17 at 1 37 22 pm](https://user-images.githubusercontent.com/39272166/47114868-d3884400-d211-11e8-8041-84e06305e0cb.png)

**Comment by jenvomo** [comment]
- [x] Fix spacing on either side of the input boxes to be even

![screen shot 2018-10-17 at 2 11 19 pm](https://user-images.githubusercontent.com/39272166/47116447-8eb2dc00-d216-11e8-9b3b-424344f23c1e.png)
